# Generated by Django 4.2.4 on 2023-11-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bulan', models.CharField(max_length=50)),
                ('No', models.IntegerField()),
                ('No_laporan', models.CharField(max_length=50)),
                ('Tanggal_laporan', models.DateField()),
                ('Tanggal_penilaian', models.DateField()),
                ('NO_SP', models.CharField(max_length=50)),
                ('Tanggal_SP', models.DateField()),
                ('Nama_debitur', models.CharField(max_length=100)),
                ('Nama_Pemberi_Tugas', models.CharField(max_length=100)),
                ('Tujuan', models.CharField(max_length=100)),
                ('Obyek', models.CharField(max_length=100)),
                ('Kota_Kabupaten', models.CharField(max_length=100)),
                ('LT', models.IntegerField()),
                ('LB', models.IntegerField()),
                ('CP', models.CharField(max_length=20)),
                ('Supervisi', models.CharField(max_length=100)),
                ('Penilai', models.CharField(max_length=100)),
                ('Pelaksana', models.CharField(max_length=100)),
                ('Fee_total', models.IntegerField()),
                ('dpp', models.IntegerField()),
                ('ppn', models.IntegerField()),
                ('Indikasi_nilai', models.IntegerField()),
                ('Kesimpulan_nilai', models.CharField(max_length=100)),
                ('Report', models.CharField(max_length=100)),
                ('Titik_koordinat', models.CharField(max_length=50)),
                ('Nama', models.CharField(max_length=100)),
                ('Jumlah_kamar', models.IntegerField()),
                ('Jumlah_kamarmandi', models.IntegerField()),
                ('Jumlah_lantai', models.IntegerField()),
                ('Lokasi', models.CharField(max_length=50)),
            ],
        ),
    ]
