# Generated by Django 4.2.4 on 2023-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_rumah',
            name='Tanggal_SP',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table_rumah',
            name='Tanggal_laporan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table_rumah',
            name='Tanggal_penilaian',
            field=models.CharField(max_length=50),
        ),
    ]
