# Generated by Django 4.2.4 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_table_rumah_pusat_kota_alter_table_rumah_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_rumah',
            name='CP',
            field=models.CharField(max_length=200),
        ),
    ]
