# Generated by Django 4.2.4 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_table_rumah_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_rumah',
            name='Lokasi',
            field=models.CharField(max_length=300),
        ),
    ]
