# Generated by Django 4.2.4 on 2023-11-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_table_rumah_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('Titik_koordinat', models.CharField(max_length=100)),
                ('Kota_Kabupaten', models.CharField(max_length=100)),
                ('LT', models.IntegerField()),
                ('LB', models.IntegerField()),
                ('Tujuan', models.CharField(max_length=255)),
                ('Obyek', models.CharField(max_length=255)),
                ('Indikasi_nilai', models.FloatField()),
                ('Jumlah_kamar', models.IntegerField()),
                ('Jumlah_kamarmandi', models.IntegerField()),
                ('Jumlah_lantai', models.IntegerField()),
                ('Pusat_kota', models.FloatField()),
                ('Prediksi', models.IntegerField(max_length=255)),
            ],
        ),
    ]
