# Generated by Django 4.2.4 on 2023-11-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_simulasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulasi',
            name='Indikasi_nilai',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='Prediksi',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='simulasi',
            name='Pusat_kota',
            field=models.CharField(max_length=50),
        ),
    ]
